// Code generated by command: go run main.go -out weighted_sum_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func computeWeightedSumAVX2(W []float64, Y []float64, indices []int) (sumW float64, sumWY float64)
// Requires: AVX, FMA3, SSE2
TEXT ·computeWeightedSumAVX2(SB), NOSPLIT, $0-88
	MOVQ   W_base+0(FP), AX
	MOVQ   Y_base+24(FP), CX
	MOVQ   indices_base+48(FP), DX
	MOVQ   indices_len+56(FP), BX
	VZEROUPPER
	VXORPD Y0, Y0, Y0
	VXORPD Y1, Y1, Y1
	XORQ   SI, SI
	MOVQ   BX, DI
	CMPQ   DI, $0x04
	JLT    tail

loop:
	MOVQ        (DX)(SI*8), DI
	MOVQ        8(DX)(SI*8), R8
	MOVQ        16(DX)(SI*8), R9
	MOVQ        24(DX)(SI*8), R10
	VMOVSD      (AX)(DI*8), X2
	VMOVSD      (AX)(R8*8), X3
	VUNPCKLPD   X3, X2, X2
	VMOVSD      (AX)(R9*8), X3
	VMOVSD      (AX)(R10*8), X4
	VUNPCKLPD   X4, X3, X3
	VINSERTF128 $0x01, X3, Y2, Y2
	VMOVSD      (CX)(DI*8), X3
	VMOVSD      (CX)(R8*8), X4
	VUNPCKLPD   X4, X3, X3
	VMOVSD      (CX)(R9*8), X4
	VMOVSD      (CX)(R10*8), X5
	VUNPCKLPD   X5, X4, X4
	VINSERTF128 $0x01, X4, Y3, Y3
	VADDPD      Y2, Y0, Y0
	VFMADD231PD Y3, Y2, Y1
	ADDQ        $0x04, SI
	MOVQ        BX, DI
	SUBQ        SI, DI
	CMPQ        DI, $0x04
	JGE         loop

tail:
	CMPQ        SI, BX
	JGE         reduce
	MOVQ        (DX)(SI*8), DI
	VMOVSD      (AX)(DI*8), X2
	VMOVSD      (CX)(DI*8), X3
	VXORPD      Y4, Y4, Y4
	VXORPD      Y5, Y5, Y5
	VINSERTF128 $0x00, X2, Y4, Y4
	VINSERTF128 $0x00, X3, Y5, Y5
	VADDPD      Y4, Y0, Y0
	VFMADD231PD Y5, Y4, Y1
	INCQ        SI
	JMP         tail

reduce:
	VEXTRACTF128 $0x01, Y0, X2
	VEXTRACTF128 $0x01, Y1, X3
	VADDPD       X2, X0, X0
	VADDPD       X3, X1, X1
	VUNPCKHPD    X0, X0, X2
	VUNPCKHPD    X1, X1, X3
	VADDSD       X2, X0, X0
	VADDSD       X3, X1, X1
	MOVSD        X0, sumW+72(FP)
	MOVSD        X1, sumWY+80(FP)
	VZEROUPPER
	RET

// func computeWeightedSumContiguousAVX2(W []float64, Y []float64) (sumW float64, sumWY float64)
// Requires: AVX, CMOV, FMA3, SSE2
TEXT ·computeWeightedSumContiguousAVX2(SB), NOSPLIT, $0-64
	MOVQ    W_base+0(FP), AX
	MOVQ    Y_base+24(FP), CX
	MOVQ    W_len+8(FP), DX
	MOVQ    Y_len+32(FP), BX
	CMPQ    BX, DX
	CMOVQLT BX, DX
	VZEROUPPER
	VXORPD  Y0, Y0, Y0
	VXORPD  Y1, Y1, Y1
	VXORPD  Y2, Y2, Y2
	VXORPD  Y3, Y3, Y3
	XORQ    BX, BX
	MOVQ    DX, SI
	CMPQ    SI, $0x08
	JLT     loop4_check

loop8:
	VMOVUPD     (AX)(BX*8), Y4
	VMOVUPD     (CX)(BX*8), Y5
	VADDPD      Y4, Y0, Y0
	VFMADD231PD Y5, Y4, Y2
	VMOVUPD     32(AX)(BX*8), Y4
	VMOVUPD     32(CX)(BX*8), Y5
	VADDPD      Y4, Y1, Y1
	VFMADD231PD Y5, Y4, Y3
	ADDQ        $0x08, BX
	MOVQ        DX, SI
	SUBQ        BX, SI
	CMPQ        SI, $0x08
	JGE         loop8

loop4_check:
	MOVQ        DX, SI
	SUBQ        BX, SI
	CMPQ        SI, $0x04
	JLT         tail_check
	VMOVUPD     (AX)(BX*8), Y4
	VMOVUPD     (CX)(BX*8), Y5
	VADDPD      Y4, Y0, Y0
	VFMADD231PD Y5, Y4, Y2
	ADDQ        $0x04, BX

tail_check:
	CMPQ BX, DX
	JGE  reduce

tail_loop:
	VMOVSD      (AX)(BX*8), X4
	VMOVSD      (CX)(BX*8), X5
	VXORPD      Y6, Y6, Y6
	VXORPD      Y7, Y7, Y7
	VINSERTF128 $0x00, X4, Y6, Y6
	VINSERTF128 $0x00, X5, Y7, Y7
	VADDPD      Y6, Y0, Y0
	VFMADD231PD Y7, Y6, Y2
	INCQ        BX
	CMPQ        BX, DX
	JLT         tail_loop

reduce:
	VADDPD       Y1, Y0, Y0
	VADDPD       Y3, Y2, Y2
	VEXTRACTF128 $0x01, Y0, X1
	VEXTRACTF128 $0x01, Y2, X3
	VADDPD       X1, X0, X0
	VADDPD       X3, X2, X2
	VUNPCKHPD    X0, X0, X1
	VUNPCKHPD    X2, X2, X3
	VADDSD       X1, X0, X0
	VADDSD       X3, X2, X2
	MOVSD        X0, sumW+48(FP)
	MOVSD        X2, sumWY+56(FP)
	VZEROUPPER
	RET
